## Literature

- a quick overview about the literature

Bernanke(2007):

- inflation makes pricing and investing processes more difficult, messes with taxing and accounting rules
- inflation leads to less public confidence in the economy and economic plicy
- low inflation "promotes growth, efficiency and stability", what is good for productivity and therefore employment
- inflation expectations determine actual inflation
- gives definition of anchored expectations: expectations are anchored when shocks dont have an influence on the long-term expectations of inflation --> shock and high inflation are transitional. when long-term expectations differ, then we have unanchored expectations
- his hypothesis on P.3: "If, on the other hand, the public reacts to a short period of higher-than-expected inflation by marking up their long-run expectation considerably, then expectations are poorly anchored."
- anchoring depends on the assumptions of the people, because they dont have full about information about everything. if this holds, than the estimation for inflation changes little, when people are confident about their estimation and they dont react on new information
- in 2007 inflation less respondive to supply shocks than in the past
- IMPORTANT: " With inflation expectations well anchored, a one-time increase in energy prices should not lead to a pennanent increase in inflation but only to a change in relative prices. A related implication is that, if inflation expectations are well anchored, changes in energy (and food) prices should have relatively little influence on "core" inflation, that is, inflation excluding the prices of food and energy."
- in summary expectations are only imperfect anchored
- surveys a good tool to measure expectations, short and long-term


Carvalho(2014):
- 


Carvalho(2021):
- long-term expectations are endogenous, short-term makes the long-term ones
- end 1990s unanchored expectations


Corsello(2019):
- uses data from ECB’s Survey of Professional Forecasters, professionals!!!
- shows, that expectations have become de-anchored
- analysis with the low inflation right before covid19
- anchoring necessary to maintain stable inflation
- gives explanation of different models how to measure anchoring
- hhs expectations are dependent on movements for energy and food prices
- reanchoring very important!


Coibion et al. (2020):
- there are important differences between expectations of professionals and normal people
- people in high income countries are inattentive towards inflation, people in countries like iran, turkey, that have high inflation rates pay attention
- ordinary people see inflation only in the volatility of consumed goods, like petrol, therefore more volatility in expectations for uninformed agents
- ordinaries people inflation expectations are not anchored
- high qualtity of hhs surveys, therefore good tool for analysis
- news about inflation, monetary policy ore statements by the CB dont have any effects on normal people only on informend specialists
- when people get an information treatment about inflation, their views change, expectations change strongly
- expectations and real inflation often differ drastically from one another, as seen in a lot of surveys
- economic environment is key for views about inflation
- S.5: "economic agents update their beliefs depending on the strengths of their priors and signals"
- shopping experience are important for formation of expecrtations ("Tomaten sind teuer geworden") --> Cavallo et al (2017) checken
- but some goods are more important --> gasoline very important, comovements between expectations and gasoline prices
- news about inflation can have an effect, but that is very disputable
- people dont know shit about monetary policy. but when they know, they update their expectations towards the real value and towards professional forecasts
- Summary for formation of expectations: people are very different in their knwoledge depending on their living experiences, economic environment. the sucessful monetary policy in adavnced countries has led to inattention by households about inflation or inflation goals


D’Acunto (2022):
- P.1:"household inflation expectations are biased upwards, dispersed across individuals, and volatile in the time series"
- Inflation expectations important for CBs
- outside crises expectations are anchored
- old models: expectations are formed rational, but that is outdated
- hhs look at grocery prices to form their expectations: increases are more important than decreases (Luca:loss aversion??)
- lifetime experiences are important: if you had lived in a country and time with high infaltion, your perception about future rates are likely higher
- hhs have higher expectations than professionals (upward biased)
- shopping prices main sources for expectations. Problem: groceries more volatile, dont represent core inflation
- the higher the volatility of your grocery products, the higher your expectations
- prices signals are important
- before covid: young people did not live trough high inflation, had lower expectations than old people how suffered through high inflation
- professionals are much more in line with actual inflation, because they have to deal with it, its their job, cognitive task
- media did not play a significant role for formation in the past


Dräger,Lamla (2012):
- dont know that much about formation of inflation expectations
- looking at updating behavior of people in the michigan survey
- Idea is to look at the participants that are interviewed twice six months later. Have they changed their expectations or not?
- findings: updating on quantitative questions every 8 months, qualitative every 16 months about one-year-ahead inflation. in recessions updating behavior increases, therefore adjustments about the expectations are correlated with the business cycle. long-term less often adjusted than short-term


Dräger and Lamla (2017):
- Uses micro-data from the michigan survey from 78-2011, since 87 same number of participants in the survey
- volatility in inflation leads to updating of expectations
- hearing news about inflation increases probability of updating
- uses again the rotating structure of the panel to analyze updating
- updating about every 8 to 16 months for (quanti/quali) short-term, and 8 to 36 months for long-term expectations --> anchoring for at least half a year
- quantitative changes only small when qualitative expectations stay the same
- differences in EU and US are maybe driven by different types of available surveys
- long-term more anchored
- professionals change their expectations, that triggers consumers
- information has no long-term effect
- imperfect information plays important role for formation of expectations about inflation

Dräger and Lamla (2018):
- analyzing co-movement of short and long-term inflation expectations
- again definition of anchoring: only short term moves, but not long-term
- expectations more anchored since mid 90ties
- looking at sensitivity of different age cohorts: are they different in their anchoring? --> yes
- older people react more and change their expectations, therefore are less anchored
- illustrates different measurement strategies for anchoring
- anchoring definition same as used by bernanke (2017)
- movement in the degree of anchoring depends on the size of shocks: only big shocks change something
- uses data from the MSC
- expectations for older cohorts remain more volatile, but in general everything gets more stable -> anchoring, but for older people much more fragile, because they experienced high inflation in the 70s
- younger cohorts react stronger to news and price changes
- expectations cruel for anchoring: if you lived trough high inflation, you have a lower degree of anchoring, inflation effects through experience long-term the expectations of consumers


Dräger and Nghiem (2018):
- approximately 50% of respondents believed that inflation over the previous twelve months had been 5% or above, at a time when actual inflation was 0.3%.


Ha et al.(2022):
- expectations in EMDE, emerging countries, are less anchored and different than in delevoped countries
- anchoring has increased, like in advanced economies


Lucas(1975):
- modelling of business cycle
- imperfect information about prices and the economy is embedded into the model
- in this behavior of the agents, their information about prices come from the market clearing prizes of the last periods, so their experiences in the past
P.1123: "the history of prices [. . .] observed by an individual is his source of information on the current state of the economy and [. . .] of information on future price."
- agents know about business cycles


Powell(2022):
- P.1: "The labor market is very strong, and inflation is much too high."
- rise of inflation greater than expected
- supply-side frictions cause present inflation
- things can change quickly when shit hits the fan
- long-term inflation still anchored!
- risk: long tenures of high inflation can increase long-term expectations (what would mean deanchoring)
- anchoring long-term expectations critical for CB policy


Weber(2021):
- inflation expectations are essential for economics
- your perception of future prices influences todays buying decisions. if this holds true expectations about future matter today
- explains upward bias
- expectations are not anchored
- expectations are formed by price signals when we go shopping. although its aonly a small portion, groceries or gasoline are very important for formation of expectations
- the more often you purchased a good, the more important price changes are for your infl. expectations
- other important factors: news coverage, media and cognitive abilities
- explains MSC and SCE surveys
- upward bias differs between demographic groups: the poorer, the higher
- detects pos. correlation between short and long-term expectations. that would mean that expectations are not anchored (or not anchored in the sense of bernanke, or the inflation goal of 2%)
- media and news coverage not that important. news about inflation, goals of CB dont reach consumers, more at coibion


## Our Hypotheses

- positive correlation between crises like corona and updating behavior
- negative correlation between grade of anchored inflation expectations and the crises of the last two years
